# Generated by Django 5.2.8 on 2026-04-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0005_bairro_cep_bairro_endereco_bairro_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.bairro'),
        ),
    ]
