# Generated by Django 5.2.8 on 2026-04-12 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0006_alter_pessoa_bairro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='nome_completo',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lider',
            name='secao',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lider',
            name='titulo_eleitor',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lider',
            name='zona',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lider',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.bairro'),
        ),
        migrations.AlterField(
            model_name='lider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
