# Generated by Django 5.2.8 on 2026-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0008_pessoa_cpf_pessoa_rg_pessoa_secao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
