# Generated by Django 5.2.8 on 2026-04-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0010_alter_pessoa_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificacoes', to='campanha.lider'),
        ),
    ]
