# Generated by Django 5.2.8 on 2026-04-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0011_lider_bonus_alter_bonus_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='meta',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.lider'),
        ),
    ]
