# Generated by Django 5.2.8 on 2026-04-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0012_lider_meta_alter_pessoa_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='campanha.lider'),
        ),
    ]
